# 1. Memory Settings (Ditambah untuk kompilasi C++)
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=512m

# 2. Arsitektur & Performa
org.gradle.parallel=true
android.useAndroidX=true
android.enablePngCrunchInReleaseBuilds=true

# 3. New Architecture (WAJIB TRUE untuk Reanimated v4)
newArchEnabled=true
hermesEnabled=true

# 4. Arsitektur CPU (Tetap sertakan x86_64 untuk emulator)
reactNativeArchitectures=arm64-v8a,x86_64

# 5. Expo & Media Settings
expo.gif.enabled=true
expo.webp.enabled=true
expo.useLegacyPackaging=true

# 6. Versi SDK (Sesuai diskusi Fase 4)
android.minSdkVersion=24
android.compileSdkVersion=36
android.targetSdkVersion=36
android.buildToolsVersion=36.0.0
android.ndkVersion=27.1.12297006
android.kotlinVersion=2.0.21

# 7. Track Player Repo
android.extraMavenRepos=[{"url":"../../node_modules/react-native-track-player/android/repo"}]

# Specifies whether the app is configured to use edge-to-edge via the app config or plugin
# WARNING: This property has been deprecated and will be removed in Expo SDK 55. Use `edgeToEdgeEnabled` or `react.edgeToEdgeEnabled` to determine whether the project is using edge-to-edge.
expo.edgeToEdgeEnabled=true

# Use this property to enable edge-to-edge display support.
# This allows your app to draw behind system bars for an immersive UI.
# Note: Only works with ReactActivity and should not be used with custom Activity.
edgeToEdgeEnabled=true

EX_DEV_CLIENT_NETWORK_INSPECTOR=true