# 1. Memory Settings (Dioptimasi untuk GitHub Actions & C++ Build)
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# 2. Arsitektur & Performa
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true
android.useAndroidX=true
android.enablePngCrunchInReleaseBuilds=true

# 3. New Architecture (Kunci Utama Reanimated v4 & TurboModules)
newArchEnabled=true
hermesEnabled=true

# 4. Arsitektur CPU
# arm64-v8a untuk device modern, x86_64 untuk emulator
reactNativeArchitectures=arm64-v8a,x86_64

# 5. Expo & Media Settings
expo.gif.enabled=false
expo.webp.enabled=true
expo.useLegacyPackaging=false
expo.jsEngine=hermes

# 6. Versi SDK (Stabilitas Tinggi untuk 2026)
android.minSdkVersion=24
android.compileSdkVersion=36
android.targetSdkVersion=36
android.buildToolsVersion=36.0.0
android.ndkVersion=27.1.12297006
android.kotlinVersion=1.9.24
android.prefabVersion=2.1.0

# 7. Track Player Repo
android.extraMavenRepos=[{"url":"../../node_modules/react-native-track-player/android/repo"}]

# 8. UI & Edge-to-Edge (Persiapan Expo 55)
edgeToEdgeEnabled=true
react.edgeToEdgeEnabled=true

# 9. Debugging
EX_DEV_CLIENT_NETWORK_INSPECTOR=true
